* Title, Abstract, Document Structure
** Title (confirm)
+A solution for Real Time Communications in Community Networks based on WebRTC+
Real-Time Communications for Organizations
** Abstract
The present project introduces the disrupting technology WebRTC (Web Real-Time Communication), that supports browser-to-browser applications without need of third party plugins. It is detailed how, since its release by Google in 2011, it's changing the way communications are understood. How to materialise a Real Time Communications in organizations, taking as example guifi.net and the opportunities that it offers: use cases, architecture design, component selection, applications available, implementation and demo.
** Project Charter
*** Motivation -> Intro
Reasons for undertaking the project
*** Objectives -> Intro
Objectives and constraints of the project
*** SWOT -> Methodology
- Risks identified early on
- Target project benefits
*** Scope -> Methodology (dismissed)
In-scope and out-of-scope items
**** attempt backup
The selected topic is very extensive, that's why it needs concretion.

Discarded parts are:
- Circuit switching and traditional telephony: The trend goes to Internet products (packet switching). For example traditional telecom product is starting to use VoIP massively (source?).

IN
packet switched, Internet, guifi

OUT
circuit switch
*** Resources -> Methodology
- Material and Human resources, its cost
*** Planning -> Methodology
** Tasks
snapshot of the tasks     tasks.org
** Document Structure (draft)
only 2 iterations, no more updates, next changes to [[../latexbuild/thesis.org]]
*** iteration 1
1. *Introduction*
   - *guifi.net architecture*
   - *Community wireless* (? not confirmed): bandwidth, delay and other parameters of wifi that affects RTC communications. Needs on connectivity
   - *User cases*: services that people need in community networks
2. *State of the art*: Other solutions proposed to solve the problem inside guifi.net and in the Internet
3. *Methodology*: WebRTC study
   - Study the feasability of WebRTC as a general solution to solve this user cases
     - Detailed description of WebRTC and deep study of its features
       - By default use open formats (vp8 / opera). Has compatibility with PSTN codec standard
       - WebRTC solves NAT traversal
     - Relation between WebRTC, signalling and RT multimedia protocols (SIP, RTP, H.323, ...)
     - Available implementations
4. *Results*: Deployment
   - if it is a good solution, design and implementation based on Guifi.net's architecture and users cases
*** iteration 2 (no more updates)
**** Introduction
***** Motivation 
***** Objectives
***** Outline
**** Fundamentals of RTC
Soft and Hard Real Time
***** Bandwidth
***** Delay
***** Signalling
***** Transport
****** Circuit switching
****** Packet switching
**** State of the art
***** Voice and video calls
***** Instant messaging
***** WebRTC
**** Methodology
***** SWOT Analysis
***** Resources
***** Planning
**** Contributions & Results
***** Architecture of guifi.net
***** Use cases
***** Architecture design
***** Component selection
***** Applications available
***** Implementation
***** /Demo/
**** Conclusions & Future Work
***** Conclusions
***** Future Work
