#+LaTeX_class: tesi_upf
#+OPTIONS: todo:nil
# #+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:nil pri:nil tags:not-in-toc
# more: http://orgmode.org/manual/Export-settings.html

#+BEGIN_LATEX
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[12pt, a4paper,twoside]{tesi_upf}

%CODIFICACIÓ
%\usepackage[latin1]{inputenc}
\usepackage[utf8]{inputenc}
%IDIOMES
\usepackage[catalan,spanish,english]{babel}

%NOMÉS PER A OBTENIR INDICACIÓ DEL MARC EN MIDA A4
%\usepackage[cam,a4,center,frame]{crop}

%PER A INCLOURE GRÀFICS I EL LOGO DE LA UPF
\usepackage{graphicx}
\usepackage{caption}
\usepackage{acronym}
\usepackage{multirow}
%FONTS TIMES O GARAMOND, 
\usepackage{times}
%\usepackage{garamond}
\usepackage{url}

\usepackage{pdfpages}
%SENSE HEADINGS: NO MODIFICAR
\pagestyle{plain}

%PER A L'ÍNDEX DE MATÈRIES
\usepackage{makeidx}
\makeindex

%ESTIL DE BIBLIOGRAFIA
\bibliographystyle{apalike}

%AQUEST DOCUMENT ÉS EN CATALÀ
\selectlanguage{english}

%EN COMPTES DE ÍNDEX, LA TAULA DE CONTINGUTS ES TITULA SUMARI
\addto\captionscatalan
  {\renewcommand{\contentsname}{\Large \sffamily Sumari}}

% ~~~~~~~~~~~~~~~~~~~~~~~~~~
% CUSTOM PACKAGES
% ~~~~~~~~~~~~~~~~~~~~~~~~~~
%\usepackage{hyperref}
\usepackage[hidelinks]{hyperref}
\usepackage{titlesec}
\setcounter{secnumdepth}{5}
% source: http://tex.stackexchange.com/questions/130795/
\usepackage{pdfpages}

\usepackage{draftwatermark}
\SetWatermarkText{DRAFT}
\SetWatermarkLightness{0.95}

%AFEGIU EN AQUESTA PART LES VOSTRES DADES
\title{Real-Time Communication for Organizations}
%\subtitle{}
\author{Pedro Vílchez}
\thyear{2015}
\department{Departament de Tecnologies de la Informació i les Comunicacions (DTIC)}
\supervisor{Miquel Oliver, Victor Pascual}

\usepackage{pgfgantt}

\begin{document}

\pdfstringdefDisableCommands{%
\let\MakeUppercase\relax
}

\frontmatter

\maketitle

\cleardoublepage


%%%%%% Dedicatòria; si no es vol posar, comenteu fins a final de dedicatòria

\noindent Dedicated to my family.

\cleardoublepage

%%%%%% Final de dedicatòria


%%%%%% Agraïments; si no es vol posar, comenteu fins a final de agraïments
\noindent {\Large \sffamily Acknowledgments}
\\[12pt] 

Special thanks to Victor Pascual and Miquel Oliver for his mentorship. Thanks to Victor Oncins and Angel Elena for his feedback and help.

Thanks to Daniel Pocock for its work on rtcquickstart.org. Thanks to webrtchacks.com and all its team for the useful articles.

Thanks to all the people that works for the democratisation of communications

Thanks for reading. Thanks for your time.

\cleardoublepage

%%%%%% Final dels agraïments

%ABSTRACT EN DOS IDIOMES. COM A MÍNIM CATALÀ. SI L'ALTRE ÉS EN CASTELLA CANVIEU EL QUE POSA ABSTRACT
\selectlanguage{english}
\section*{\Large \sffamily Abstract}

The present project introduces the disrupting technology WebRTC (Web Real-Time Communication), that supports browser-to-browser applications without need of third party plugins. It is detailed how, since its release by Google in 2011, it's evolving and changing the way communications are understood. How to materialise a Real Time Communications in organizations, taking as example guifi.net and the opportunities that it offers: use cases, architecture design, applications available, implementation and demo.

\selectlanguage{catalan}
\vspace*{\fill}
\section*{\Large \sffamily Resum}

Aquest projecte

\selectlanguage{spanish}
\vspace*{\fill}
\section*{\Large \sffamily Resumen}

Este proyecto

\vspace*{\fill}

\selectlanguage{english}
\cleardoublepage
%FIN DE ABSTRACTE

%PREFACI OPCIONAL. SI NO ES VOL, COMENTEU FINS EL FINAL DE PREFACI
%{\bf Prefaci}
%
%\cleardoublepage
%FINAL DE PREFACI

r
%TAULA DE CONTINGUTS: OBLIGATÒRIA
\selectlanguage{english}
\tableofcontents

%INDEX DE FIGURES; NOMÉS ES POSA SI HI HA FIGURES
\listoffigures
%Fa que aparegui al sumari
\addcontentsline{toc}{chapter}{List of figures}

%INDEX DE TAULES; NOMÉS ES POSA SI HI HA TAULES
\listoftables
%Fa que aparegui al sumari
\addcontentsline{toc}{chapter}{List of tables}

%COMENÇA EL TEXT
\mainmatter

% no indent for every new paragraph
%\setlength{\parindent}{0em}
% \linespread{1.5} % space between every new line 1.5 (I do not like)
% space between paragraphsx
%\setlength{\parskip}{\baselineskip}
#+END_LATEX

* Introduction
** Motivation
In the other bachelor's thesis \cite{vilchez2014comnet} I worked 2 ideas: together we can do networks, it is simple to start. Even so, in cities like Barcelona it is easy to find persons that do not understand what is guifi.net, probably for two reasons: there is a very competitive communications market in cities and the complexity to understand a commons model from the consumer point of view. In the case of zones where there is no investment of large operators, the things change: persons need internet, and they struggle to understand the commons model.

The implementation of other services besides Internet, could help certain persons to understand the advantages of commons network, add value to the network. There are services based on contents that are difficult to maintain but there is a service that can be easily applied on a large scale: RTC. It is something to plan and wait until people start using it. Because is communication with close environment. We are social.

Also, from the guifi point of view, is a challenge, there were some attempts to implement a RTC system but they failed. With WebRTC, let’s try again!
** Objectives
- Free and secure communication between users using own RTC system and commons network infrastructure.
- Backward compatible with VoIP network. Hence, users can communicate to other VoIP operators from inside and/or outside guifi.net.
- An architecture design of an RTC system that fits the community network scenario.
- Ease of installation and use of the RTC.
** Outline
This document is organised in 5 chapters.

*Chapter 1 Introduction* introduces the project. The motivation to start this project and the high level objectives to achieve.

*Chapter 2 Fundamentals of RTC* presents the basics of fill.

*Chapter 3 State of the Art* discusses the state of the art of fill.

*Chapter 4 Contributions and Results* contains a description of the methodology used to fill.

*Chapter 5 Conclusions and Future Work*, the results obtained. Finally, the last Chapter presents the conclusions and future work
* Fundamentals of RTC
** Communications
*** Circuit switching and traditional telephony
*** Packet switching and Internet
** Real-time
* State of the art
** Important mechanisms
** Voice and video calls
*** VoIP
** Instant messaging
** WebRTC
*** Security
* Methodology
** TODO SWOT Analysis of WebRTC
Table [[tab:swot]] shows the analysis of Strengs, Weaknesses, Opportunities and Threat about this project.
*** Strengths
- Ease of use: real-time communication is supported without the need for additional applications or plug-ins.
- It helps to solve connectivity problems caused by NAT, Firewall, etc.
- It solved the problem with audio and video codecs.
- It is based on open technology.
- It has well general acceptance in both worlds: enterprise and community.
- The communication between peers can be P2P
- WebRTC standard do not specify signalling: it can be used in very different scenarios.
- The communication channel between peers is encrypted
*** Weaknesses
- There are detractors of WebRTC, this includes some web browsers.
- There is a a long discussion about what video codec should be supported in web browsers.
- WebRTC uses different RTP packets than SIP. So a gateway is needed.
- Security compromised in VPN-tunnels, where the true IP address of the user can be read.
*** Opportunities
- For VoIP, WebRTC could be a web softphone. Easy to install, easy to update.
- A WebRTC audio call could be routed to traditional telephony.
- It uses javascript as programming language, this language has the wider community.
- It encourages a new generation of web applications.
*** Threats
- WebRTC standard do not specify signalling: this can produce a positive or negative fragmentation of projects. Positive fragmentation: different projects for different applications. Negative fragmentation: divided effort.
- Is a work in progress technology, it is being changed.
** Scope

There are a lots of RTC systems for different purposes. This project focuses in the work of IETF organization and the Internet. Guifi.net is part of Internet, and has additional constraints to take in account.

Dismissed well-known RTC systems built for organizations is from the ITU organization. It only was introduced in the Fundamentals Chapter as "Circuit switching and traditional telephony".

Preferences in terms of technologies chosen, they should be open standard, open source software, with royalty free patent. If this is not possible, it will be notified, and will be used temporarily another technology until a new one appear and substitute it.

** Resources

There are costs related to the activity of this project in terms of equipment and human effort.

Table [[tab:eqre]] shows the equipment resources and its economic estimation. Observations:
- Guifi.net connectivity to Barcelona, a reachable IPv4 10.0.0.0/8[fn:1] has not direct cost.
- Nearly all software involved is open source and has no direct cost.
- Usually the cost of installation it’s greater or equal than the cost of equipment.

#+CAPTION: Equipment resources
#+NAME: tab:eqre
| Material                                   | Estimated cost (euro) |
|--------------------------------------------+-----------------------|
| guifi.net equipments in my home            |                   200 |
| PC with virtualization capabilities [home] |                  1000 |
| guifi.net equipments in university         |                  1000 |
| PC with Internet public IPv4 [university]  |                   300 |
| Laptop                                     |                   400 |
| ATA x 2                                    |                    60 |
| Old phone x 2                              |                     2 |
|--------------------------------------------+-----------------------|
| Total                                      |                  2962 |

# C-c + to sum all rows in a column
# S-insertchar to insert the result

The human effort part was financed by the university in the form of a grant to the author, representing a cost of 2800 euro. A bachelor’s thesis corresponds in Europe to 500 hours of work.

This implies a total cost of approximately 6000 euro

** Planning
The project can be separated in two phases. The first phase is a long preamble of studying VoIP and WebRTC. The second phase is an agile plan. Figure \ref{fig:gantt1} shows the two phases in a gantt chart.

# In the case of a pgfgantt, you have to create the "figure" inside
# to refer it, use a \ref instead of a orgmode local link
#+BEGIN_LATEX
\begin{figure}[htb]
\centering

\begin{ganttchart}[hgrid, vgrid]{1}{12}
\gantttitle{2014}{5}
\gantttitle{2015}{7} \\
\gantttitlelist{8,9,10,11,12,1,2,3,4,5,6,7}{1} \ganttnewline
\ganttbar{VoIP study}{2}{5} \ganttnewline
\ganttbar{WebRTC study}{6}{9} \ganttnewline
\ganttbar{Scrum plan}{10}{11}
\end{ganttchart}

\caption{\label{fig:gantt1}General gantt chart}
\end{figure}
#+END_LATEX

In the first phase, while studying VoIP the intention was to work about VoIP and guifi.net. But Miquel Oliver encouraged me to do it about WebRTC. He presented me Victor Pascual, a SIP and WebRTC expert. It was hard to realise a convenient project, because this technology involves lots of protocols, other technologies, and it’s being modified now. In this phase It were settled the necessary
concepts to start the project.

The second phase is an agile plan, inspired by the Scrum methodology. Scrum is one of the Agile methods[fn:3] used for software development. The important fact is that promotes adaptive planning and flexible response to change. Scrum, particularly, is a general method that should be adapted to a concrete scenario.

The Scrum Team consists of a Product Owner, the Development Team, and a Scrum Master. The work of the scrum team according to the Scrum Guide[fn:2] is /deliver products iteratively and incrementally, maximizing opportunities for feedback. Incremental deliveries of "Done" product ensure a potentially useful version of working product is always available/. The roles are
- Product Owner: /is responsible for maximizing the value of the product and the work of the Development Team/
- Development Team: /consists of professionals who do the work of delivering a potentially releasable Increment of "Done" product at the end of each Sprint/
- Scrum Master: /is responsible for ensuring Scrum is understood and enacted/

/The heart of Scrum is a *Sprint*, a time-box of one month or less during which a "Done", usable, and potentially releasable product Increment is created/

*** Scrum plan
It is necessary to adapt the different concepts that comprise the scrum methodology for this particular project.

Roles:
- Product Owner (in some way, stakeholders): Mentors, University, people interested in the project. The author is interested in the output of the project because is volunteer in guifi.net.
- Development Team: assumed by the author
- Scrum Master: assumed by the author, optionally could be assumed by mentors.

This means that the author has to see the project with different points of view.

The Sprint time is approximately one week, because it is assumed that the minimum time-box possible to do a release of the product is one week. The product comprise two parts: the theory (documentation, memory) and practice (how this theory is fitted to the real world experiments).

Figure \ref{fig:gantt2} shows the Scrum plan with the different sprint phases (s1, s2, s3, s4) and important milestones:
- d1: project charter and tasks, delivery to mentors
- d2: first consistent draft memory, delivery to mentors
- d3: set title and abstract to the thesis, delivery to university
- d4: thesis, delivery to assigned tribunal

#+BEGIN_LATEX
\begin{figure}[htb]
\centering

\begin{ganttchart}[
hgrid,
vgrid,
x unit=3.5mm,
time slot format=isodate
]{2015-05-12}{2015-06-18}
\gantttitlecalendar{year, month=name, week} \\
\ganttbar{s1}{2015-05-13}{2015-05-22} \ganttnewline
\ganttbar{s2}{2015-05-23}{2015-05-29} \ganttnewline
\ganttbar{s3}{2015-05-30}{2015-06-05} \ganttnewline
\ganttbar{s4}{2015-06-06}{2015-06-15} \ganttnewline
\ganttmilestone{d1}{2015-05-18} \ganttnewline
\ganttmilestone{d2}{2015-05-22} \ganttnewline
\ganttmilestone{d3}{2015-05-25} \ganttnewline
\ganttmilestone{d4}{2015-06-15}
\end{ganttchart}

\caption{\label{fig:gantt2}Scrum plan gantt chart}
\end{figure}

\vspace*{\fill}
#+END_LATEX

*** Metatools
To ensure the scrum plan and the project, different tools were used:
- Emacs orgmode: is a plain text syntax and software that facilitates different operations
  - nested concepts: It is possible to fold and unfold nested concepts different parts. This brings facilities to take different points of view of the project.
  - write the memory of the project and export to UPF publication constraints.
  - diary: used as autoevaluation tool. Time spent in some operations. Place to record when was discovered something.
  - tasks: to write things to do and mark them as TODO and DONE. To see overall progress of the project.
- Git: is a distributed version control system that helps to ensure the work is not lost. It can has a local and remote copy of all different states (commits) of the project. It is very flexible to do changes and apply.
- Github[fn:4] repository: is a social network that uses git and has the largest community. Good place to host and share open source projects. This project is hosted as a repository in https://github.com/pedro-nonfree/guifi-webrtc. Featured files:
  - diary.org: record of activity in time
  - tasks.org: parts to do for the project
  - doc directory: independent parts written before starting the memory, or that needs isolation
    - doc/index.org: organise the different files of this directory
  - latexbuild directory: place where emacs orgmode thesis file is exported to latex and compiled to PDF
    - thesis.org: source code of memory
    - thesis.pdf: memory

* Contributions & Results
** Architecture of guifi.net
** Use cases
** Architecture design
** Component selection
** Applications available
** Implementation
** /Demo/
* Conclusions & Future Work
** Conclusions
** Future Work
* Fake
#+BEGIN_LATEX
\bibliography{bibliography}
\cleardoublepage



\backmatter
\printindex





\end{document}


%NUMERACIÓ DE LA PÀGINA EXTERIOR EXCEPTE EN LA PRIMERA PÀGINA DE CADA CAPÍTOL
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyfoot{}
\fancyfoot[RO]{\thepage}
\fancyfoot[LE]{\thepage}


%MUTIPLES ÍNDEX
%En el preàmbul
\usepackage{multind}
\makeindex{authors}
%Introducció d'entrades la forma
\index{authors}{Einstein}
%Situació de l'Índex
\printindex{authors}{Author index}
%Cal eliminar les comandes \usepakage{makeidx} \makeindex \printindex
%cal exacutar des de la línia de comandes makeindex authors
#+END_LATEX

* Footnotes

[fn:1] range of IP's used by guifi.net and private networks

[fn:2] http://www.scrumguides.org/docs/scrumguide/v1/scrum-guide-us.pdf

[fn:3] There are different metodologies grouped into agile. The process started with the write of the Agile Manifesto (12 principles) http://agilemanifesto.org/iso/en/principles.html. Since February 2001, this manifesto remains unchanged.

[fn:4] the web implementation is proprietary software, but it can be easily migrated to other open source tools such as http://gitlab.com or http://gogs.io/
